# Generated by Django 3.2.23 on 2024-02-27 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0004_auto_20240227_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donoraccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
