# Generated by Django 3.2.23 on 2024-02-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_alter_payment_djstripe_owner_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('paid', True)), fields=('user', 'description', 'amount'), name='unique_paid_payments'),
        ),
    ]
