# Generated by Django 3.2.23 on 2024-02-27 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0009_auto_20240227_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='djstripe_owner_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
