# Generated by Django 3.2.23 on 2024-01-23 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0004_scholarshipapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='demographic',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='school',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('about_me', models.TextField()),
                ('website_link', models.URLField()),
                ('business_proposal', models.FileField(upload_to='business_proposals/')),
                ('fee_structure', models.FileField(blank=True, null=True, upload_to='fee_structures/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
