# Generated by Django 3.2.23 on 2024-01-24 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0006_pitchdeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='partnership_outcome',
            field=models.TextField(blank=True, null=True, verbose_name='How can we ensure you get the most out of this partnership?'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='product_suite_overview',
            field=models.TextField(blank=True, null=True, verbose_name='Product Suite Overview'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='question1',
            field=models.TextField(blank=True, null=True, verbose_name='Why do you want to be involved with the Belonging Foundation?'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='question2',
            field=models.TextField(blank=True, null=True, verbose_name='How will this partnership benefit your community?'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='url_api_details',
            field=models.TextField(blank=True, null=True, verbose_name='URLs / API Details'),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='business_proposal',
            field=models.FileField(blank=True, null=True, upload_to='business_proposals/'),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('navigation_link', models.URLField(blank=True)),
                ('social_media_link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='venue_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('time_zone', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='events/photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='events/photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='events/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='events/videos/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
