# Generated by Django 3.2.23 on 2024-02-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
