# Generated by Django 3.2.23 on 2024-02-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ecommerce_website',
            field=models.URLField(blank=True, max_length=255, verbose_name='eCommerce Website'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_website',
            field=models.URLField(blank=True, max_length=255, verbose_name='Profile Website'),
        ),
    ]
