# Generated by Django 3.2.23 on 2024-02-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='referee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=255)),
                ('nominee_email', models.EmailField(max_length=254)),
                ('nominee_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('justification', models.TextField()),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referee.referee')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referee.scholarship')),
            ],
        ),
    ]
