# Generated by Django 3.2.23 on 2024-02-12 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referee', '0002_auto_20240211_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('why_sponsor', models.TextField(verbose_name='Why do you want to be a sponsor?')),
                ('qualifications', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
