# Generated by Django 3.2.23 on 2024-02-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0003_sponsorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsorapplication',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsorapplication',
            name='referee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referee.referee'),
        ),
        migrations.AddField(
            model_name='sponsorapplication',
            name='rejection_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
