# Generated by Django 3.2.23 on 2024-02-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0004_auto_20240212_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorapplication',
            old_name='is_approved',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='is_rejected',
        ),
    ]
