# Generated by Django 3.2.23 on 2024-03-01 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0007_alter_referee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='referee.scholarship'),
        ),
    ]
