# Generated by Django 3.2.23 on 2024-03-01 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referee', '0008_alter_referral_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referee',
            name='referee_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
