# Generated by Django 3.2.23 on 2024-01-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('donor', 'Foundation Donor'), ('applicant', 'Scholarship Applicant'), ('recipient', 'Scholarship Recipient'), ('host', 'Auction Host'), ('bidder', 'Bidder'), ('owner', 'Local Shop Owner')], default='student', max_length=10),
        ),
    ]
