# Generated by Django 3.2.23 on 2024-02-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('donor', 'Foundation Donor'), ('applicant', 'Scholarship Applicant'), ('recipient', 'Scholarship Recipient'), ('host', 'Auction Host'), ('bidder', 'Bidder'), ('owner', 'Local Shop Owner')], default='student', max_length=10),
        ),
    ]
