# Generated by Django 3.2.23 on 2024-02-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('username',)},
        ),
    ]
