# Generated by Django 3.2.23 on 2024-01-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0003_bid_bidder_item_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
                ('question3', models.TextField()),
                ('demographic', models.CharField(choices=[('high_school', 'High School Junior/Senior'), ('post_secondary', 'Post-Secondary Freshman/Sophomore'), ('black_sheep', 'Self-Identified Black Sheep')], max_length=50)),
                ('school', models.CharField(max_length=200)),
            ],
        ),
    ]
