# Generated by Django 3.2.23 on 2024-02-04 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0003_alter_customuser_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='age',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='scholarship_pdfs/'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='question1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='question2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='question3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='education_level',
            field=models.CharField(choices=[('high_school', 'High School'), ('college', 'College'), ('graduate_school', 'Graduate School'), ('blacksheep', 'Blacksheep')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
