# Generated by Django 3.2.23 on 2024-02-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0005_auto_20240203_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='business_desciption',
            field=models.URLField(blank=True, null=True),
        ),
    ]
