# Generated by Django 3.2.23 on 2024-02-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0006_vendorapplication_business_desciption'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
