# Generated by Django 3.2.23 on 2024-02-06 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0008_auto_20240204_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarshipapplication',
            old_name='question1',
            new_name='squestion1',
        ),
        migrations.RenameField(
            model_name='scholarshipapplication',
            old_name='question2',
            new_name='squestion2',
        ),
        migrations.RenameField(
            model_name='scholarshipapplication',
            old_name='question3',
            new_name='squestion3',
        ),
        migrations.RenameField(
            model_name='vendorapplication',
            old_name='question1',
            new_name='vquestion1',
        ),
        migrations.RenameField(
            model_name='vendorapplication',
            old_name='question2',
            new_name='vquestion2',
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_applications', models.ManyToManyField(blank=True, to='belonging.ScholarshipApplication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to=settings.AUTH_USER_MODEL)),
                ('vendor_applications', models.ManyToManyField(blank=True, to='belonging.VendorApplication')),
            ],
        ),
    ]
