# Generated by Django 3.2.23 on 2024-02-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0009_auto_20240206_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
