# Generated by Django 3.2.23 on 2024-02-07 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0011_alter_scholarshipapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorapplication',
            name='business_desciption',
            field=models.TextField(blank=True, null=True, verbose_name='Brief description of your business'),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
