# Generated by Django 3.2.23 on 2024-02-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0012_auto_20240207_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Customer account'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff account'),
        ),
    ]
