# Generated by Django 3.2.23 on 2024-02-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0017_sponsorapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorApplication',
        ),
    ]
