# Generated by Django 3.2.23 on 2024-02-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belonging', '0018_delete_sponsorapplication'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='pitchdeck',
            name='user',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='scholarship_applications',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='vendor_applications',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='PitchDeck',
        ),
        migrations.DeleteModel(
            name='Referee',
        ),
        migrations.DeleteModel(
            name='ScholarshipApplication',
        ),
        migrations.DeleteModel(
            name='UserApplication',
        ),
        migrations.DeleteModel(
            name='VendorApplication',
        ),
    ]
