# Generated by Django 3.2.23 on 2024-02-27 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('belonging', '0019_auto_20240221_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='belonging_vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
