# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: |
        docker build -t ashtongkinnell/beloning-prod:latest .
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username ashtongkinnell --password-stdin
        docker push ashtongkinnell/beloning-prod:latest

    - name: Update Server
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
        ssh -i <(echo "$KEY") $USERNAME@$HOST 'bash -s' < ./deploy.sh
