name: Test Database Connection

on:
  push:
    branches:
      - main

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ensure this matches your project's Python version

    - name: Install dependencies
      run: |
        pip install pyodbc
        # Install any other dependencies your script may require

    - name: Test Database Connection
      env:
        DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
      run: python test_db_connection.py
