# Generated by Django 3.2.23 on 2024-02-21 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denial_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('college', 'College'), ('graduate_school', 'Graduate School'), ('blacksheep', 'Blacksheep')], max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='scholarship_pdfs/')),
                ('squestion1', models.TextField(blank=True, null=True)),
                ('squestion2', models.TextField(blank=True, null=True)),
                ('squestion3', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denial_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('vquestion1', models.TextField(blank=True, null=True, verbose_name='Why do you want to be involved with the Belonging Foundation?')),
                ('vquestion2', models.TextField(blank=True, null=True, verbose_name='How will this partnership benefit your community?')),
                ('product_suite_overview', models.TextField(blank=True, null=True, verbose_name='Product Suite Overview')),
                ('url_api_details', models.TextField(blank=True, null=True, verbose_name='URLs / API Details')),
                ('partnership_outcome', models.TextField(blank=True, null=True, verbose_name='How can we ensure you get the most out of this partnership?')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('business_proposal', models.FileField(blank=True, null=True, upload_to='business_proposals/')),
                ('fee_structure', models.FileField(blank=True, null=True, upload_to='fee_structures/')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=50, null=True)),
                ('business_desciption', models.TextField(blank=True, null=True, verbose_name='Brief description of your business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_applications', models.ManyToManyField(blank=True, to='applicant.ScholarshipApplication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to=settings.AUTH_USER_MODEL)),
                ('vendor_applications', models.ManyToManyField(blank=True, to='applicant.VendorApplication')),
            ],
        ),
        migrations.CreateModel(
            name='PitchDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='pitch_decks/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
