# Generated by Django 3.2.23 on 2024-02-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='scholarship',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='applicant.scholarship'),
        ),
    ]
