# Generated by Django 3.2.23 on 2024-02-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_scholarshipapplication_scholarship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='title',
            new_name='scholarship',
        ),
    ]
