# Generated by Django 3.2.23 on 2024-02-29 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_rename_title_scholarship_scholarship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='scholarship',
            new_name='title',
        ),
    ]
