# Generated by Django 3.2.23 on 2024-03-06 14:38

from django.db import migrations, models
import referee.models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_auto_20240305_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='referee_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=referee.models.Referee),
        ),
    ]
